//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumental.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckType()
        {
            this.CheckProcess = new HashSet<CheckProcess>();
            this.DocumentCheck = new HashSet<DocumentCheck>();
            this.DocumentProcess = new HashSet<DocumentProcess>();
        }
    
        public int IdCheckType { get; set; }
        public int IdTypeProcess { get; set; }
        public int IdChecck { get; set; }
        public bool Active { get; set; }
    
        public virtual Check Check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckProcess> CheckProcess { get; set; }
        public virtual TypeProcess TypeProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentCheck> DocumentCheck { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentProcess> DocumentProcess { get; set; }
    }
}
