//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumental.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GDEntities : DbContext
    {
        public GDEntities()
            : base("name=GDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audit> Audit { get; set; }
        public virtual DbSet<Check> Check { get; set; }
        public virtual DbSet<CheckProcess> CheckProcess { get; set; }
        public virtual DbSet<CheckType> CheckType { get; set; }
        public virtual DbSet<Directory> Directory { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<DocumentCheck> DocumentCheck { get; set; }
        public virtual DbSet<DocumentProcess> DocumentProcess { get; set; }
        public virtual DbSet<Expedient> Expedient { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<TypeProcess> TypeProcess { get; set; }
        public virtual DbSet<UserGD> UserGD { get; set; }
    }
}
