//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumental.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Expedient = new HashSet<Expedient>();
        }
    
        public int IdProject { get; set; }
        public string CodProject { get; set; }
        public string NameProject { get; set; }
        public Nullable<int> IdRepresent { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool UseProject { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Avance { get; set; }
    
        public virtual Directory Directory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expedient> Expedient { get; set; }
    }
}
