//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int IdAudit { get; set; }
        public string NameUser { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
