//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckType
    {
        public CheckType()
        {
            this.CheckProcess = new HashSet<CheckProcess>();
            this.DocumentCheck = new HashSet<DocumentCheck>();
            this.DocumentProcess = new HashSet<DocumentProcess>();
        }
    
        public int IdCheckType { get; set; }
        public int IdTypeProcess { get; set; }
        public int IdChecck { get; set; }
        public bool Active { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual ICollection<CheckProcess> CheckProcess { get; set; }
        public virtual TypeProcess TypeProcess { get; set; }
        public virtual ICollection<DocumentCheck> DocumentCheck { get; set; }
        public virtual ICollection<DocumentProcess> DocumentProcess { get; set; }
    }
}
