//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentCheck
    {
        public int IdDocumentCheck { get; set; }
        public Nullable<int> IdDocument { get; set; }
        public int IdCheckType { get; set; }
        public int IdState { get; set; }
        public int IdType { get; set; }
        public bool Requiered { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual CheckType CheckType { get; set; }
        public virtual Document Document { get; set; }
        public virtual State State { get; set; }
        public virtual Type Type { get; set; }
    }
}
