//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentProcess
    {
        public int IdDocumentProcess { get; set; }
        public int IdCheckType { get; set; }
        public int IdExpedient { get; set; }
        public Nullable<int> IdState { get; set; }
        public Nullable<int> IdType { get; set; }
        public bool Requiered { get; set; }
        public bool Active { get; set; }
    
        public virtual CheckType CheckType { get; set; }
        public virtual Expedient Expedient { get; set; }
    }
}
