//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GDEntities : DbContext
    {
        public GDEntities()
            : base("name=GDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Audit> Audit { get; set; }
        public DbSet<Check> Check { get; set; }
        public DbSet<CheckProcess> CheckProcess { get; set; }
        public DbSet<CheckType> CheckType { get; set; }
        public DbSet<Directory> Directory { get; set; }
        public DbSet<Document> Document { get; set; }
        public DbSet<DocumentCheck> DocumentCheck { get; set; }
        public DbSet<DocumentProcess> DocumentProcess { get; set; }
        public DbSet<Expedient> Expedient { get; set; }
        public DbSet<Project> Project { get; set; }
        public DbSet<Record> Record { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<State> State { get; set; }
        public DbSet<Type> Type { get; set; }
        public DbSet<TypeProcess> TypeProcess { get; set; }
        public DbSet<UserGD> UserGD { get; set; }
    }
}
