//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGD
    {
        public int IdUser { get; set; }
        public int IdDirectory { get; set; }
        public int IdRol { get; set; }
        public string NameUser { get; set; }
        public string Password { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool Active { get; set; }
    
        public virtual Directory Directory { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
